### ISSUE TITLE
BossBarを有効にすると、1秒ごとにエラーが記録される

### ISSUE THREAD

**Issue by ucchyocean** [ucchyocean/ExpTimer#22]
BossBarを有効にすると、1秒ごとにエラーが記録される。
スタックトレースは下記の通り。

<pre>
[00:03:48] [Server thread/WARN]: [ExpTimer] Task #3 for ExpTimer v2.6.0 generated an exception
java.lang.IllegalArgumentException: Progress must be between 0.0 and 1.0 (100.0)
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.craftbukkit.v1_14_R1.boss.CraftBossBar.setProgress(CraftBossBar.java:158) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at com.github.ucchyocean.et.BossBarManager.setMessage(BossBarManager.java:40) ~[?:?]
	at com.github.ucchyocean.et.TimerTask.refreshBossbar(TimerTask.java:522) ~[?:?]
	at com.github.ucchyocean.et.TimerTask.run(TimerTask.java:288) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1023) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:971) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:816) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
</pre>

**Comment by ucchyocean** [comment]
BossBarの値には、0.0 から 1.0 の間の値を指定しなければならない仕様のようだが、ExpTimerからは 0.0 から 100.0 の値を指定してしまっている模様。100分の1しなければならないのでは。

**Comment by ucchyocean** [comment]
Fixed 
動作確認OK
